// Re-export lucide-react icons with Ubuntu-system-icon naming
// lucide-react's design language matches Ubuntu's Yaru symbolic icons

export {
    Terminal as TerminalIcon,
    Folder as FolderIcon,
    User as UserIcon,
    FileText as FileTextIcon,
    Briefcase as BriefcaseIcon,
    Calendar as CalendarIcon,
    Settings as SettingsIcon,
    Wifi as WifiOnIcon,
    WifiOff as WifiOffIcon,
    Volume2 as VolumeIcon,
    VolumeX as VolumeMuteIcon,
    Sun as BrightnessIcon,
    Battery as BatteryIcon,
    Power as PowerIcon,
    Lock as LockIcon,
    RotateCcw as RestartIcon,
    Home as HomeIcon,
    File as FileIcon,
    Download as DownloadIcon,
    X as CloseIcon,
    Minus as MinimizeIcon,
    Square as MaximizeIcon,
    Bluetooth as BluetoothIcon,
    BellOff as DoNotDisturbIcon,
    PlaneTakeoff as AirplaneIcon,
    ChevronRight,
    ChevronLeft,
    ChevronUp,
    ChevronDown,
    Globe,
    Moon,
    Laptop,
    Clock,
} from 'lucide-react';
